// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyManagement.API.Data;

namespace PolicyManagement.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200728140109_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyManagement.Data.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiveVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PolicyGroupingId")
                        .HasColumnType("int");

                    b.Property<int>("VersionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyGroupingId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("PolicyManagement.Data.PolicyGrouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PolicyGroupingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyGroupingId");

                    b.ToTable("PolicyGroups");
                });

            modelBuilder.Entity("PolicyManagement.Data.PolicyVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<decimal>("VersionNumber")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyVersions");
                });

            modelBuilder.Entity("PolicyManagement.Data.Policy", b =>
                {
                    b.HasOne("PolicyManagement.Data.PolicyGrouping", null)
                        .WithMany("Policies")
                        .HasForeignKey("PolicyGroupingId");
                });

            modelBuilder.Entity("PolicyManagement.Data.PolicyGrouping", b =>
                {
                    b.HasOne("PolicyManagement.Data.PolicyGrouping", null)
                        .WithMany("Folders")
                        .HasForeignKey("PolicyGroupingId");
                });

            modelBuilder.Entity("PolicyManagement.Data.PolicyVersion", b =>
                {
                    b.HasOne("PolicyManagement.Data.Policy", null)
                        .WithMany("Versions")
                        .HasForeignKey("PolicyId");
                });
#pragma warning restore 612, 618
        }
    }
}
